#!/bin/bash
ROOT=$(python3 -c 'import os, sys; print(os.path.normpath(os.path.abspath(sys.argv[1])))' "${CLAUDE_PROJECT_DIR:-$(pwd)}")
LIST="$ROOT/.claude/hooks/frozen-paths.txt"
[ -f "$LIST" ] || exit 0
INPUT=$(cat)
TOOL=$(printf '%s' "$INPUT" | jq -r '.tool_name // empty')

deny() {
  echo "BLOCKED by .claude/hooks/guard-frozen.sh: '$1' is frozen (Phase 1 UI closed on 2026-10-07; AGENTS.md rules 2 and 3). Phase 2 only rewires data: markup, styles, assets, motion, sound and the verification harness stay as they are, and the visual baseline is never regenerated by the agent. If this change is genuinely required, stop and ask the user; only they can edit .claude/hooks/frozen-paths.txt." >&2
  exit 2
}

patterns() { grep -vE '^[[:space:]]*(#|$)' "$LIST"; }

is_frozen() {
  local rel="$1" pat
  while IFS= read -r pat; do
    case "$pat" in
      *'/**') [[ "$rel" == "${pat%/**}" || "$rel" == "${pat%/**}"/* ]] && return 0 ;;
      *) [[ "$rel" == "$pat" ]] && return 0 ;;
    esac
  done < <(patterns)
  return 1
}


case "$TOOL" in
  Edit|Write|NotebookEdit)
    FILE=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // .tool_input.notebook_path // empty')
    [ -z "$FILE" ] && exit 0
    case "$FILE" in /*) ;; *) FILE="$ROOT/$FILE" ;; esac
    FILE=$(python3 -c 'import os, sys; print(os.path.normpath(sys.argv[1]))' "$FILE")
    REL="${FILE#"$ROOT"/}"
    is_frozen "$REL" && deny "$REL"
    ;;
  Bash)
    CMD=$(printf '%s' "$INPUT" | jq -r '.tool_input.command // empty')
    [ -z "$CMD" ] && exit 0
    if printf '%s' "$CMD" | grep -qE 'visual:baseline|update-snapshots|(playwright|npm run visual)[^|;&]*[[:space:]]-u([[:space:]]|$)'; then
      deny "tests/visual/__snapshots__ (baseline regeneration)"
    fi
    WRITES='(^|[;&|(`[:space:]])(sed[[:space:]]+(-[a-zA-Z]+[[:space:]]+)*-[a-zA-Z]*i|perl[[:space:]]+-[a-zA-Z]*i|rm|rmdir|mv|cp|tee|truncate|touch|ln|rsync|install|chmod|dd|patch|unzip|tar|node[[:space:]]+-e|python3?[[:space:]]+-c|git[[:space:]]+(checkout|restore|rm|mv))([[:space:]]|$)|--write|--fix|[^0-9&<=>-]>>?[[:space:]]*[^&>[:space:]]|^>>?'
    printf '%s' "$CMD" | grep -qE "$WRITES" || exit 0
    regexes=$(patterns | awk '
      function esc(s) { gsub(/[][\\.^$*+?(){}|\/]/, "\\\\&", s); return s }
      {
        base = $0; sub(/\/\*\*$/, "", base)
        files = files (files == "" ? "" : "|") esc(base)
        anc = base
        while (sub(/\/[^\/]*$/, "", anc)) if (!(anc in seen)) { seen[anc] = 1; ancs = ancs (ancs == "" ? "" : "|") esc(anc) }
      }
      END { print files; print ancs }')
    files_re=$(printf '%s\n' "$regexes" | sed -n 1p)
    anc_re=$(printf '%s\n' "$regexes" | sed -n 2p)
    hit=$(printf '%s' "$CMD" | grep -oE -- "(^|[^A-Za-z0-9_.-])(\./)?($files_re)(/|[^A-Za-z0-9_.-]|$)" | head -1)
    [ -n "$hit" ] && deny "$(printf '%s' "$hit" | sed -E 's/^[^A-Za-z0-9_.(]+//; s/[^A-Za-z0-9_.)*-]+$//')"
    hit=$(printf '%s' "$CMD" | grep -oE -- "(^|[^A-Za-z0-9_.-])(\./)?($anc_re)/?([[:space:]\"';&|)]|$)" | head -1)
    [ -n "$hit" ] && deny "$(printf '%s' "$hit" | sed -E 's/^[^A-Za-z0-9_.(]+//; s/[^A-Za-z0-9_.)-]+$//') (contains frozen files)"
    ;;
esac
exit 0
